// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3ZONbn-3uvYdtJZUsCKqaTbQZWc5AgcU',
    appId: '1:944305260432:web:85343a1ec36e0fe9855515',
    messagingSenderId: '944305260432',
    projectId: 'holbegram-e67ca',
    authDomain: 'holbegram-e67ca.firebaseapp.com',
    storageBucket: 'holbegram-e67ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIiknbedI-f11UNZDBq3PpBXF3UdMMEaA',
    appId: '1:944305260432:android:ef5b062a729aa248855515',
    messagingSenderId: '944305260432',
    projectId: 'holbegram-e67ca',
    storageBucket: 'holbegram-e67ca.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3ZONbn-3uvYdtJZUsCKqaTbQZWc5AgcU',
    appId: '1:944305260432:web:d5cb165e65b53fcc855515',
    messagingSenderId: '944305260432',
    projectId: 'holbegram-e67ca',
    authDomain: 'holbegram-e67ca.firebaseapp.com',
    storageBucket: 'holbegram-e67ca.firebasestorage.app',
  );

}